"""extract_river_flow.py - annual water-year river flow -> data_in_depth_value.

Pulls `C_<code>` channel flow (TAF) for the 17 river-flow nodes from the
trend-report export (via TrendReport; s0002 excluded -> 115 scenarios), sums the
monthly TAF across each **water year (Oct-Sep)** to a single annual volume, and
emits raw per-year rows for `data_in_depth_value`.

- period = 'annual', unit = TAF (one row per scenario/node/water_year).
- Water year Y = Oct (Y-1) .. Sep (Y). Only years with all 12 months are summed.
- No percent-of-capacity (flow, not storage) and no aggregates.
- Everything derived (exceedance, box, mean, CV) is computed live by the API.

Output -> etl/data_in_depth/output/river_flow_values.sql (gitignored). Apply:
    psql "$DATABASE_URL" -f etl/data_in_depth/output/river_flow_values.sql
Prereqs: create_data_in_depth_value_table.sql + seed_data_in_depth_river_flow_subjects.sql applied.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import List, Optional, Sequence

import pandas as pd

try:
    from .trend_report import TrendReport, DEFAULT_PATH
except ImportError:  # pragma: no cover
    from trend_report import TrendReport, DEFAULT_PATH

log = logging.getLogger("extract_river_flow")

RIVER_NODES: List[str] = [
    "AMR004", "FTR003", "FTR029", "MCD005", "MOK028", "SAC000", "SAC049",
    "SAC122", "SAC148", "SAC257", "SAC289", "SJR070", "SJR127", "STS011",
    "TRN111", "TUO003", "YUB002",
]
PERIOD = "annual"
UNIT_TAF = "TAF"
MONTHS_PER_WY = 12
VALUE_TABLE = "data_in_depth_value"
DEFAULT_OUT_DIR = Path("etl/data_in_depth/output")


def build_series(tr: TrendReport, scenarios: Optional[Sequence[str]] = None) -> pd.DataFrame:
    """Annual (water-year) TAF sums per (scenario, node, water_year)."""
    cvars = [f"C_{c}" for c in RIVER_NODES]
    long = tr.to_long(variables=cvars, scenarios=scenarios, unit=UNIT_TAF, dropna=True)
    if long.empty:
        raise ValueError("No C_<node> TAF rows found")

    found = {v[2:] for v in long["variable"].unique()}
    missing = [c for c in RIVER_NODES if c not in found]
    if missing:
        log.warning("river nodes with no C_ TAF data: %s", missing)

    df = long.copy()
    # Water year (Oct-Sep): months Oct/Nov/Dec belong to the next calendar year's WY.
    df["water_year"] = df["date"].dt.year + (df["date"].dt.month >= 10).astype(int)
    df["subject_code"] = df["variable"].str[2:]           # strip 'C_'
    df["source_variable"] = df["variable"]

    g = (df.groupby(["scenario", "subject_code", "source_variable", "water_year"])["value"]
            .agg(value="sum", n="count").reset_index())
    incomplete = int((g["n"] != MONTHS_PER_WY).sum())
    if incomplete:
        log.warning("dropping %d partial water-years (< %d months)", incomplete, MONTHS_PER_WY)
    g = g[g["n"] == MONTHS_PER_WY].copy()

    g["subject_kind"] = "entity"
    g["period"] = PERIOD
    g["unit_code"] = UNIT_TAF
    return g[["scenario", "subject_kind", "subject_code", "source_variable",
              "period", "water_year", "value", "unit_code"]].reset_index(drop=True)


def _q(s: str) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def generate_value_sql(records: pd.DataFrame, batch_size: int = 5000) -> str:
    """Batched INSERT ... SELECT FROM (VALUES ...) upserts; ids resolved by join."""
    lines = [
        f"-- River flow (annual water-year TAF) values for {VALUE_TABLE}",
        f"-- {len(records)} rows | generated by etl/data_in_depth/scripts/extract_river_flow.py",
        "\\set ON_ERROR_STOP on", "BEGIN;", "",
    ]
    recs = list(records.itertuples(index=False))
    for i in range(0, len(recs), batch_size):
        chunk = recs[i:i + batch_size]
        vals = ",\n".join(
            f"  ({_q(r.scenario)},{_q(r.subject_kind)},{_q(r.subject_code)},{_q(r.source_variable)},"
            f"{_q(r.period)},{int(r.water_year)},{r.value:.4f},{_q(r.unit_code)})"
            for r in chunk
        )
        lines.append(f"INSERT INTO {VALUE_TABLE}")
        lines.append("  (scenario_short_code, data_in_depth_subject_id, source_variable, period, water_year, value, unit_id)")
        lines.append("SELECT v.scenario, s.id, v.source_variable, v.period, v.water_year, v.value, u.id")
        lines.append(f"FROM (VALUES\n{vals}\n) AS v(scenario, subject_kind, subject_code, source_variable, period, water_year, value, unit_code)")
        lines.append("JOIN data_in_depth_subject s ON s.subject_kind = v.subject_kind AND s.short_code = v.subject_code")
        lines.append("JOIN unit u ON u.short_code = v.unit_code")
        lines.append("ON CONFLICT (scenario_short_code, data_in_depth_subject_id, source_variable, period, water_year, unit_id)")
        lines.append("DO UPDATE SET value = EXCLUDED.value, updated_at = NOW(), updated_by = coeqwal_current_operator();")
        lines.append("")
    lines += ["COMMIT;", ""]
    return "\n".join(lines)


def _main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Extract annual water-year river flow into data_in_depth_value SQL.")
    p.add_argument("--path", default=DEFAULT_PATH)
    p.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    p.add_argument("--scenarios", nargs="*", help="limit scenarios (default: all 115)")
    p.add_argument("--batch-size", type=int, default=5000)
    p.add_argument("--dry-run", action="store_true", help="report summary; write nothing")
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    tr = TrendReport.load(args.path)
    df = build_series(tr, scenarios=args.scenarios)

    log.info("value rows=%d | scenarios=%d | nodes=%d | water_years=%d-%d",
             len(df), df["scenario"].nunique(), df["subject_code"].nunique(),
             int(df["water_year"].min()), int(df["water_year"].max()))

    if args.dry_run:
        log.info("dry-run: nothing written")
        print(df.head(6).to_string(index=False))
        return 0

    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "river_flow_values.sql").write_text(generate_value_sql(df, args.batch_size))
    log.info("wrote river_flow_values.sql (%d rows)", len(df))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
