"""extract_delta_salinity.py - April & September Delta X2 -> data_in_depth_value.

Pulls `X2_PRV_KM` (Delta 2-psu isohaline position, km) for every scenario from
the trend-report export (via TrendReport; s0002 excluded -> 115 scenarios),
samples the April and September value of each water year, and emits raw per-year
rows for `data_in_depth_value`.

- Subject: X2 (subject_kind='metric', no location).
- period = 'april' / 'sept'; unit = 'km'; one row per (scenario, period, water_year).
- water_year = calendar year of the sampled month (April/Sep of year Y are in WY Y).
- No aggregates. Everything derived (exceedance, box, mean, CV) is computed live
  by the API.

Unit note: the trend report labels the unit 'KM', but the DB `unit` lookup
short_code is lowercase 'km'. We select the 'KM' column but EMIT 'km' so the
generated SQL's `JOIN unit ON short_code` resolves.

Output -> etl/data_in_depth/output/delta_salinity_values.sql (gitignored). Apply:
    psql "$DATABASE_URL" -f etl/data_in_depth/output/delta_salinity_values.sql
Prereqs: create_data_in_depth_value_table.sql + seed_data_in_depth_delta_subjects.sql applied.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import pandas as pd

try:
    from .trend_report import TrendReport, DEFAULT_PATH
except ImportError:  # pragma: no cover
    from trend_report import TrendReport, DEFAULT_PATH

log = logging.getLogger("extract_delta_salinity")

VARIABLE = "X2_PRV_KM"          # CalSim var (c-part X2-POSITION-PREV)
SUBJECT_CODE = "X2"
SUBJECT_KIND = "metric"
PERIODS: Dict[str, int] = {"april": 4, "sept": 9}   # period label -> calendar month
UNIT_TREND = "KM"               # unit as labelled in the trend report
UNIT_DB = "km"                  # unit short_code in the DB lookup (lowercase)
VALUE_TABLE = "data_in_depth_value"
DEFAULT_OUT_DIR = Path("etl/data_in_depth/output")


def build_series(tr: TrendReport, scenarios: Optional[Sequence[str]] = None) -> pd.DataFrame:
    """April/September X2 (km) per (scenario, period, water_year)."""
    long = tr.to_long(variables=[VARIABLE], scenarios=scenarios, unit=UNIT_TREND, dropna=True)
    if long.empty:
        raise ValueError(f"No {VARIABLE} ({UNIT_TREND}) rows found")

    df = long[long["date"].dt.month.isin(PERIODS.values())].copy()
    month_to_period = {m: p for p, m in PERIODS.items()}
    df["period"] = df["date"].dt.month.map(month_to_period)
    df["water_year"] = df["date"].dt.year
    df["subject_kind"] = SUBJECT_KIND
    df["subject_code"] = SUBJECT_CODE
    df["source_variable"] = VARIABLE
    df["value"] = df["value"].astype(float)
    df["unit_code"] = UNIT_DB
    return df[["scenario", "subject_kind", "subject_code", "source_variable",
              "period", "water_year", "value", "unit_code"]].reset_index(drop=True)


def _q(s: str) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def generate_value_sql(records: pd.DataFrame, batch_size: int = 5000) -> str:
    """Batched INSERT ... SELECT FROM (VALUES ...) upserts; ids resolved by join."""
    lines = [
        f"-- Delta salinity X2 (April & September, km) values for {VALUE_TABLE}",
        f"-- {len(records)} rows | generated by etl/data_in_depth/scripts/extract_delta_salinity.py",
        "\\set ON_ERROR_STOP on", "BEGIN;", "",
    ]
    recs = list(records.itertuples(index=False))
    for i in range(0, len(recs), batch_size):
        chunk = recs[i:i + batch_size]
        vals = ",\n".join(
            f"  ({_q(r.scenario)},{_q(r.subject_kind)},{_q(r.subject_code)},{_q(r.source_variable)},"
            f"{_q(r.period)},{int(r.water_year)},{r.value:.4f},{_q(r.unit_code)})"
            for r in chunk
        )
        lines.append(f"INSERT INTO {VALUE_TABLE}")
        lines.append("  (scenario_short_code, data_in_depth_subject_id, source_variable, period, water_year, value, unit_id)")
        lines.append("SELECT v.scenario, s.id, v.source_variable, v.period, v.water_year, v.value, u.id")
        lines.append(f"FROM (VALUES\n{vals}\n) AS v(scenario, subject_kind, subject_code, source_variable, period, water_year, value, unit_code)")
        lines.append("JOIN data_in_depth_subject s ON s.subject_kind = v.subject_kind AND s.short_code = v.subject_code")
        lines.append("JOIN unit u ON u.short_code = v.unit_code")
        lines.append("ON CONFLICT (scenario_short_code, data_in_depth_subject_id, source_variable, period, water_year, unit_id)")
        lines.append("DO UPDATE SET value = EXCLUDED.value, updated_at = NOW(), updated_by = coeqwal_current_operator();")
        lines.append("")
    lines += ["COMMIT;", ""]
    return "\n".join(lines)


def _main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Extract April/September Delta X2 into data_in_depth_value SQL.")
    p.add_argument("--path", default=DEFAULT_PATH)
    p.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    p.add_argument("--scenarios", nargs="*", help="limit scenarios (default: all 115)")
    p.add_argument("--batch-size", type=int, default=5000)
    p.add_argument("--dry-run", action="store_true", help="report summary; write nothing")
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    tr = TrendReport.load(args.path)
    df = build_series(tr, scenarios=args.scenarios)

    log.info("value rows=%d | scenarios=%d | periods=%s | water_years=%d-%d",
             len(df), df["scenario"].nunique(), sorted(df["period"].unique()),
             int(df["water_year"].min()), int(df["water_year"].max()))

    if args.dry_run:
        log.info("dry-run: nothing written")
        print(df.head(6).to_string(index=False))
        return 0

    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "delta_salinity_values.sql").write_text(generate_value_sql(df, args.batch_size))
    log.info("wrote delta_salinity_values.sql (%d rows)", len(df))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
