"""extract_wyt.py - Extract Sacramento Valley water-year-type into SQL inserts.

Reads the CalSim trend-report export via :class:`TrendReport`, pulls the
``WYT_SAC_`` variable for every scenario, samples the **May** value of each
year, and emits batched ``INSERT ... ON CONFLICT`` statements for the
``scenario_water_year_type`` table.

Why May: WYT_SAC is stored as a monthly series but is not constant within a
water year, so a specific sampling month is required. The May value of
calendar year ``Y`` becomes ``(scenario, water_year=Y, wyt)``.

Year range: the source starts 1921-10, so the first May is 1922 -> water years
run 1922..2021 (100 rows/scenario). If you instead want to label each row by the
water-year *start* year (WY1922 -> 1921), set ``--year-offset -1``.

Output goes to ``etl/data_in_depth/output/`` (gitignored); apply with:
    psql "$DATABASE_URL" -f etl/data_in_depth/output/wyt_sac.sql
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import List, Optional, Sequence

import pandas as pd

try:
    from .trend_report import TrendReport, DEFAULT_PATH
except ImportError:  # pragma: no cover
    from trend_report import TrendReport, DEFAULT_PATH

log = logging.getLogger("extract_wyt")

VARIABLE = "WYT_SAC_"          # parsed variable (raw B-part is WYT_SAC__sNNNN)
SAMPLE_MONTH = 5               # May
TABLE = "scenario_water_year_type"
WYT_MIN, WYT_MAX = 1, 5
DEFAULT_OUT = Path("etl/data_in_depth/output/wyt_sac.sql")


def extract_records(
    tr: TrendReport,
    variable: str = VARIABLE,
    month: int = SAMPLE_MONTH,
    year_offset: int = 0,
    scenarios: Optional[Sequence[str]] = None,
) -> pd.DataFrame:
    """Return a tidy DataFrame [scenario_short_code, water_year, wyt].

    Samples ``month`` from each year of ``variable`` across all (or the given)
    scenarios. ``year_offset`` is added to the sampled May's calendar year.
    """
    long = tr.to_long(variables=[variable], scenarios=scenarios, prefer_unit=None, dropna=True)
    if long.empty:
        raise ValueError(f"No data for variable {variable!r}")

    sample = long[long["date"].dt.month == month].copy()
    if sample.empty:
        raise ValueError(f"No rows for month={month} in {variable!r}")

    sample["water_year"] = sample["date"].dt.year + year_offset
    # WYT is an integer classification stored as float; round defensively.
    sample["wyt"] = sample["value"].round().astype(int)

    records = (
        sample[["scenario", "water_year", "wyt"]]
        .rename(columns={"scenario": "scenario_short_code"})
        .sort_values(["scenario_short_code", "water_year"])
        .reset_index(drop=True)
    )
    _validate(records)
    return records


def _validate(records: pd.DataFrame) -> None:
    """Fail loud on the invariants the target table enforces."""
    dupes = records.duplicated(subset=["scenario_short_code", "water_year"]).sum()
    if dupes:
        raise ValueError(f"{dupes} duplicate (scenario, water_year) rows - check the sampling month")
    bad = records[(records["wyt"] < WYT_MIN) | (records["wyt"] > WYT_MAX)]
    if not bad.empty:
        raise ValueError(
            f"{len(bad)} wyt values outside {WYT_MIN}..{WYT_MAX}: {sorted(bad['wyt'].unique())}"
        )


def _sql_escape(code: str) -> str:
    return code.replace("'", "''")


def generate_sql(records: pd.DataFrame, table: str = TABLE, batch_size: int = 100) -> str:
    """Render batched INSERT ... ON CONFLICT upserts as one SQL script."""
    n_scen = records["scenario_short_code"].nunique()
    yr_lo, yr_hi = int(records["water_year"].min()), int(records["water_year"].max())
    lines: List[str] = [
        f"-- Water-year-type (Sacramento Valley) inserts for {table}",
        f"-- Source variable: {VARIABLE} (May sample). Generated by etl/data_in_depth/scripts/extract_wyt.py",
        f"-- {len(records)} rows | {n_scen} scenarios | water years {yr_lo}-{yr_hi}",
        "\\set ON_ERROR_STOP on",
        "BEGIN;",
        "",
    ]

    rows = list(records.itertuples(index=False))
    for start in range(0, len(rows), batch_size):
        chunk = rows[start : start + batch_size]
        values = ",\n".join(
            f"  ('{_sql_escape(r.scenario_short_code)}', {int(r.water_year)}, {int(r.wyt)})"
            for r in chunk
        )
        lines.append(f"INSERT INTO {table} (scenario_short_code, water_year, wyt) VALUES")
        lines.append(values)
        lines.append(
            "ON CONFLICT (scenario_short_code, water_year) DO UPDATE SET\n"
            "  wyt = EXCLUDED.wyt,\n"
            "  updated_at = NOW(),\n"
            "  updated_by = coeqwal_current_operator();"
        )
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def _main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Extract WYT_SAC May values into scenario_water_year_type inserts.")
    p.add_argument("--path", default=DEFAULT_PATH, help=f"trend-report CSV (default: {DEFAULT_PATH})")
    p.add_argument("--out", default=str(DEFAULT_OUT), help=f"output .sql (default: {DEFAULT_OUT})")
    p.add_argument("--variable", default=VARIABLE)
    p.add_argument("--month", type=int, default=SAMPLE_MONTH, help="sampling month (5=May)")
    p.add_argument("--year-offset", type=int, default=0,
                   help="added to the sampled May's calendar year (use -1 for water-year start label)")
    p.add_argument("--batch-size", type=int, default=100, help="rows per INSERT")
    p.add_argument("--scenarios", nargs="*", help="limit to these scenarios (default: all)")
    p.add_argument("--dry-run", action="store_true", help="report summary; do not write the .sql")
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    tr = TrendReport.load(args.path)
    records = extract_records(tr, variable=args.variable, month=args.month,
                              year_offset=args.year_offset, scenarios=args.scenarios)

    dist = records["wyt"].value_counts().sort_index().to_dict()
    log.info("scenarios=%d rows=%d water_years=%d-%d wyt_dist=%s",
             records["scenario_short_code"].nunique(), len(records),
             int(records["water_year"].min()), int(records["water_year"].max()), dist)

    if args.dry_run:
        log.info("dry-run: no file written")
        print(records.head(8).to_string(index=False))
        return 0

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate_sql(records, batch_size=args.batch_size))
    log.info("wrote %s (%d rows)", out, len(records))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
