#!/usr/bin/env bash
# cloud9_snapshot.sh
#
# Read-only inventory of the Cloud9 environment. Captures versions,
# configs, and host info so a Linux dev host can be compared against
# the supported Cloud9 setup.
#
# Run on Cloud9 from the repo root:
#   bash scripts/cloud9_snapshot.sh > docs/CLOUD9_INVENTORY.md
#
# Or, write straight to the docs file:
#   bash scripts/cloud9_snapshot.sh --write
#
# Never modifies state. Safe to rerun anytime Cloud9 changes.

set -uo pipefail

WRITE_TO_FILE=0
OUTPUT_PATH="docs/CLOUD9_INVENTORY.md"

for arg in "$@"; do
  case "$arg" in
    --write) WRITE_TO_FILE=1 ;;
    --output=*) OUTPUT_PATH="${arg#--output=}"; WRITE_TO_FILE=1 ;;
    -h|--help)
      sed -n '2,15p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# helpers
section() { printf '\n## %s\n\n' "$1"; }

cmd_or_missing() {
  # Print the output of a command in a fenced code block, or note "(not installed)".
  local label="$1"; shift
  printf '### %s\n\n' "$label"
  if command -v "$1" >/dev/null 2>&1; then
    printf '```\n'
    "$@" 2>&1 || true
    printf '```\n\n'
  else
    printf '_%s not installed on this host._\n\n' "$1"
  fi
}

mask_secret() {
  # Mask anything that looks like a password in a URL like postgresql://user:pw@host
  sed 's#:[^:@/]*@#:***@#g'
}

# emit the report
emit() {
  printf '# Cloud9 environment inventory\n\n'
  printf '_Generated by `scripts/cloud9_snapshot.sh` at %s._\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '_Reference spec for a Linux dev host that wants to mirror Cloud9. Rerun anytime Cloud9 changes._\n'

  section "Host"
  cmd_or_missing "Operating system" uname -a
  printf '### OS release\n\n'
  if [ -r /etc/os-release ]; then
    printf '```\n'; cat /etc/os-release; printf '```\n\n'
  else
    printf '_/etc/os-release not readable._\n\n'
  fi
  cmd_or_missing "Disk free" df -h /

  section "Python"
  cmd_or_missing "python3 --version" python3 --version
  printf '### Active venv\n\n'
  if [ -n "${VIRTUAL_ENV:-}" ]; then
    printf '```\nVIRTUAL_ENV=%s\n```\n\n' "$VIRTUAL_ENV"
    if command -v pip >/dev/null 2>&1; then
      printf '### pip freeze\n\n```\n'
      pip freeze 2>&1 | sort || true
      printf '```\n\n'
    fi
  else
    printf '_No venv activated. Activate the project venv before running this snapshot to capture its packages._\n\n'
  fi

  section "rclone"
  cmd_or_missing "rclone version" rclone version
  printf '### Configured remotes\n\n'
  if command -v rclone >/dev/null 2>&1; then
    printf '```\n'
    rclone listremotes 2>&1 || true
    printf '```\n\n'
  else
    printf '_rclone not installed._\n\n'
  fi

  section "AWS"
  cmd_or_missing "aws --version" aws --version
  printf '### Caller identity\n\n'
  if command -v aws >/dev/null 2>&1; then
    printf '```\n'
    aws sts get-caller-identity 2>&1 || true
    printf '```\n\n'
    printf '### Configured region\n\n```\n'
    aws configure get region 2>&1 || true
    printf '```\n\n'
  else
    printf '_aws CLI not installed._\n\n'
  fi

  section "Docker"
  cmd_or_missing "docker --version" docker --version

  section "Postgres client"
  cmd_or_missing "psql --version" psql --version
  printf '### DATABASE_URL (masked)\n\n'
  if [ -n "${DATABASE_URL:-}" ]; then
    printf '```\n%s\n```\n\n' "$(printf '%s\n' "$DATABASE_URL" | mask_secret)"
  else
    printf '_DATABASE_URL not set._\n\n'
  fi
  printf '### SUPERUSER_URL (masked)\n\n'
  if [ -n "${SUPERUSER_URL:-}" ]; then
    printf '```\n%s\n```\n\n' "$(printf '%s\n' "$SUPERUSER_URL" | mask_secret)"
  else
    printf '_SUPERUSER_URL not set._\n\n'
  fi

  section "Git"
  cmd_or_missing "git --version" git --version
  if command -v git >/dev/null 2>&1 && git rev-parse --show-toplevel >/dev/null 2>&1; then
    printf '### Repo HEAD\n\n```\n'
    git rev-parse --abbrev-ref HEAD 2>&1 || true
    git log -1 --format='%h %s (%ci)' 2>&1 || true
    printf '```\n\n'
  fi

  section "How to mirror this on a Linux dev host (unsupported)"
  printf 'Run:\n\n```bash\nbash scripts/setup_dev_env.sh\nbash scripts/check_env.sh\n```\n\n'
  printf 'Both helpers are best-effort and unmaintained for macOS or Windows. If anything in `scripts/check_env.sh` reports `FAIL`, compare against the sections above.\n'
}

# output dispatch
if [ "$WRITE_TO_FILE" -eq 1 ]; then
  mkdir -p "$(dirname "$OUTPUT_PATH")"
  emit > "$OUTPUT_PATH"
  echo "Wrote inventory to $OUTPUT_PATH" >&2
else
  emit
fi
